/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsSitemapDotxmlRouteImport } from './routes/news-sitemap[.]xml'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilSlugRouteImport } from './routes/perfil.$slug'
import { Route as MateriaSlugRouteImport } from './routes/materia.$slug'
import { Route as InstitucionalPageRouteImport } from './routes/institucional.$page'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMateriasNovaRouteImport } from './routes/admin.materias.nova'
import { Route as AdminMateriasSlugRouteImport } from './routes/admin.materias.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSitemapDotxmlRoute = NewsSitemapDotxmlRouteImport.update({
  id: '/news-sitemap.xml',
  path: '/news-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilSlugRoute = PerfilSlugRouteImport.update({
  id: '/perfil/$slug',
  path: '/perfil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaSlugRoute = MateriaSlugRouteImport.update({
  id: '/materia/$slug',
  path: '/materia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalPageRoute = InstitucionalPageRouteImport.update({
  id: '/institucional/$page',
  path: '/institucional/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriasNovaRoute = AdminMateriasNovaRouteImport.update({
  id: '/materias/nova',
  path: '/materias/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriasSlugRoute = AdminMateriasSlugRouteImport.update({
  id: '/materias/$slug',
  path: '/materias/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/busca': typeof BuscaRoute
  '/news-sitemap.xml': typeof NewsSitemapDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/institucional/$page': typeof InstitucionalPageRoute
  '/materia/$slug': typeof MateriaSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/materias/$slug': typeof AdminMateriasSlugRoute
  '/admin/materias/nova': typeof AdminMateriasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/busca'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/admin/login'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/busca'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/admin/login'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/busca'
    | '/news-sitemap.xml'
    | '/sitemap.xml'
    | '/admin/login'
    | '/categoria/$slug'
    | '/institucional/$page'
    | '/materia/$slug'
    | '/perfil/$slug'
    | '/admin/materias/$slug'
    | '/admin/materias/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuscaRoute: typeof BuscaRoute
  NewsSitemapDotxmlRoute: typeof NewsSitemapDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  InstitucionalPageRoute: typeof InstitucionalPageRoute
  MateriaSlugRoute: typeof MateriaSlugRoute
  PerfilSlugRoute: typeof PerfilSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-sitemap.xml': {
      id: '/news-sitemap.xml'
      path: '/news-sitemap.xml'
      fullPath: '/news-sitemap.xml'
      preLoaderRoute: typeof NewsSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$slug': {
      id: '/perfil/$slug'
      path: '/perfil/$slug'
      fullPath: '/perfil/$slug'
      preLoaderRoute: typeof PerfilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materia/$slug': {
      id: '/materia/$slug'
      path: '/materia/$slug'
      fullPath: '/materia/$slug'
      preLoaderRoute: typeof MateriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional/$page': {
      id: '/institucional/$page'
      path: '/institucional/$page'
      fullPath: '/institucional/$page'
      preLoaderRoute: typeof InstitucionalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materias/nova': {
      id: '/admin/materias/nova'
      path: '/materias/nova'
      fullPath: '/admin/materias/nova'
      preLoaderRoute: typeof AdminMateriasNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materias/$slug': {
      id: '/admin/materias/$slug'
      path: '/materias/$slug'
      fullPath: '/admin/materias/$slug'
      preLoaderRoute: typeof AdminMateriasSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMateriasSlugRoute: typeof AdminMateriasSlugRoute
  AdminMateriasNovaRoute: typeof AdminMateriasNovaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMateriasSlugRoute: AdminMateriasSlugRoute,
  AdminMateriasNovaRoute: AdminMateriasNovaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuscaRoute: BuscaRoute,
  NewsSitemapDotxmlRoute: NewsSitemapDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  InstitucionalPageRoute: InstitucionalPageRoute,
  MateriaSlugRoute: MateriaSlugRoute,
  PerfilSlugRoute: PerfilSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
